// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class WebProjectSuitesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void signinerr() {
    driver.Navigate().GoToUrl("http://localhost/web%20project/ProjectGroup6/NGMart/login_reg.php");
    driver.FindElement(By.Id("login_email")).Click();
    driver.FindElement(By.Id("login_email")).SendKeys("anjanavaradan@gmail.com");
    driver.FindElement(By.Id("login_pass")).Click();
    driver.FindElement(By.Id("login_pass")).SendKeys("sdhk,");
    driver.FindElement(By.CssSelector("input:nth-child(6)")).Click();
    {
      string value = driver.FindElement(By.Id("login_email")).GetAttribute("value");
      Assert.That(value, Is.EqualTo(" \" \""));
    }
  }
  [Test]
  public void signinsuccess() {
    driver.Navigate().GoToUrl("http://localhost/web%20project/ProjectGroup6/NGMart/login_reg.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1296, 688);
    driver.FindElement(By.Id("login_email")).Click();
    driver.FindElement(By.Id("login_email")).SendKeys("anubenoyarackal912@gmail.com");
    driver.FindElement(By.Id("login_pass")).Click();
    driver.FindElement(By.Id("login_pass")).SendKeys("Alaapi@123");
    driver.FindElement(By.CssSelector("input:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.LinkText("Anu Benoy")).Text, Is.EqualTo("Anu Benoy"));
  }
  [Test]
  public void addtocartsuccess() {
    driver.Navigate().GoToUrl("http://localhost/web%20project/ProjectGroup6/NGMart/login_reg.php");
    driver.Manage().Window.Size = new System.Drawing.Size(518, 664);
    driver.FindElement(By.Id("login_email")).Click();
    driver.FindElement(By.Id("login_email")).SendKeys("anubenoyarackal912@gmail.com");
    driver.FindElement(By.Id("login_pass")).Click();
    driver.FindElement(By.Id("login_pass")).SendKeys("Alaapi@123");
    driver.FindElement(By.Id("insert")).Click();
    js.ExecuteScript("window.scrollTo(0,639.111083984375)");
    driver.FindElement(By.CssSelector(".itembox:nth-child(2) button")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".itembox:nth-child(2) img"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.LinkText("Logout"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    Assert.That(driver.FindElement(By.Id("ss")).Text, Is.EqualTo("1"));
  }
}
